project:
  type: website
  output-dir: docs

website:
  title: "Zachary Himmelsbach"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - teaching.qmd
    tools:
    - icon: twitter
      href: https://twitter.com/z_himmelsbach
    - icon: github
      href: https://github.com/zacharyhimmelsbach

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

